codecov:
  require_ci_to_pass: yes
  ignore:
    - "adapters/ent"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 39.90%

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: no
