codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 20%

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: no
