[package]
name = "notion-echo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["tokio_rt", "async"] }
napi-derive = "2"
tokio = { version = "1.36.0", features = ["rt"] }
teloxide = "0.12.2"

[build-dependencies]
napi-build = "1"
